"""Add login attempts

Revision ID: 402e8efce509
Revises: 72eb6cf5b156
Create Date: 2026-08-03 15:47:14.220899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402e8efce509'
down_revision = '72eb6cf5b156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###